- README.md
> [FIX] README.md Edit Contributors

- apps/setting/views.py
- static/css/setting/myhome_detail.css
- templates/setting/myhome_detail.html
- templates/setting/myhome_form.html
집 등록 -> 집 이름 중복 확인하지 않았거나 빈칸이 남아있으면 폼 제출 못하게 막았습니다.
집 관리 -> 집 정보 update 할 때 집 이름 중복 확인, 중복 확인 안 했거나 빈칸이 남아있으면 폼 제출 막기, 아무것도 입력 안 하면 기존 집 이름 유지하도록 했습니다.
> [FEAT] 집 정보 변경 & 등록 시 집 이름 중복 확인, 빈칸 경고

- static/css/setting/roommate_list.css
- templates/setting/myhome_detail.html
- templates/setting/roommate_list.html
2순위 기능
1. 룸메이트 프로필 보기
2. 룸메이트 넘기기 버튼 구현
> [FEAT] 룸메이트 프로필 보기 / 넘기기 버튼

- apps/home/urls.py
- apps/home/views.py
- static/js/home/date_todo.js
- templates/home/date_todo/date_todo.html
1. 내용
- 할 일 삭제하기 ajax를 변경했습니당..
- 할 일 등록 때 form validation을 거쳐야할 거 같은데 이거는 일단 잠깐 후순위로 미루고 다른 거 부터 하겠습니당
> [FEAT] 할 일 삭제하기 ajax 구현 및 오류 수정

- apps/home/urls.py
- apps/home/views.py
- static/js/home/date_todo.js
- static/js/home/move_date.js
- static/js/home/utils.js
- templates/home/date_todo/date_todo.html
- templates/home/date_todo/date_todo_base.html
- 카테고리 변경은 형식 나온 다음에 해보겠습니당..ㅎㅎ
> [FEAT] 할 일 수정(카테고리 변경은 아직..) & 할 일 내일하기 & 할 일 페이지에서 날짜 이동

- apps/home/urls.py
- apps/home/utils.py
- apps/home/views.py
- apps/login/views.py
- static/js/home/move_date.js
- templates/home/date_todo/date_todo_base.html
- templates/home/date_todo/prev_date_todo.html
- templates/login/mypage.html
- 한 일
1) 오늘 이전 날짜의 경우 할 일 수정 불가능하게 만들기
: [apps/home/views.py] [apps/home/urls.py] [static/js/home/move_date.js]
2) 캘린더에 오늘 표시(진짜 "오늘" 들어가게 함)
: [apps/home/utils.py] 캘린더 뷰 불러오는 부분의 format_date 함수 부분 수정
> [FEAT] 오늘 이전 날짜의 경우 할 일 수정 불가능 & 캘린더에 오늘 표시

- apps/home/urls.py
- apps/home/views.py
- apps/login/views.py
- static/js/home/date_todo.js
- static/js/home/home_cate.js
- static/js/home/move_date.js
- templates/home/date_todo/date_todo.html
- 한일
1) 카테고리 추가 모달 구현
2) 카테고리 추가 모달에서 이름 중복 여부 체크
3) 카테고리 추가 기능 구현(ajax)
> [FEAT] 카테고리 추가 기능 구현

- templates/base.html
- templates/login/intro.html
한 것
1. 메인 네비게이션바에서 집이 없는 경우와 로그인하지 않은 경우 -> 생활관리 메뉴 안 보이게
2. intro.html 에서 로그인하지 않은 경우 -> 시작하기 버튼 링크 연결
> [FIX] navbar 유저별 변경 & 시작하기 링크 연결

- apps/home/views.py
- static/js/home/date_todo.js
- static/js/home/home_cate.js
- templates/home/date_todo/date_todo.html
- 카테고리 추가는 생각해보니 redirect로 해도 괜찮겠다 싶어서 변경 했습니당
- 할 일 삭제하기 ajax가 담당 없음에서 동작하지 않아서 변경했습니당
> [FIX]  할 일 삭제하기 ajax 수정 및 카테고리 추가 redirect로 변경

- apps/login/forms.py
- apps/login/views.py
- templates/login/login.html
- templates/login/mypage.html
- templates/login/user_update.html
로그인 화면에 회원가입으로 이동하는 버튼 추가랑 로그인 실패 시 로그인 화면에 알림 뜨고 회원정보 수정 부분 닉네임이랑 성별만 고칠 수 있게 변경했습니다.
> [FIX] 로그인 화면에 버튼 추가 + 로그인 실패시 알림

- apps/home/views.py
- static/css/home/date_todo.css
- static/js/home/date_todo.js
- templates/home/date_todo/date_todo.html
- 할 일 수정하기 ajax 기능 수정하기(date_todo.js 주석 참고 해주세요)
- 할 일 수정하기 모달 내용 변경
1) 담당없음 : 유저는 못건듬
2) 내 할 일 탭 : 다 수정 가능(단, 담당없음으로 수정은 불가능)
> [FIX] 할 일 수정하기

- apps/home/urls.py
- apps/home/views.py
- static/js/home/date_todo.js
- static/js/home/home_cate.js
- templates/home/date_todo/date_todo.html
- 담당 추가하기 버튼 구현
1) 현재 접속해있는 유저와 다른 유저에게 일을 할당한 경우 ajax
2) 현재 접속해있는 유저와 같은 유저에게 일을 할당한 경우 reload로 본인 할일 페이지로 이동
- 할 일 추가하기 views.py 로직 수정
카테고리를 항상 기타로 넣게 해놔서 이부분 수정했습니당
> [FEAT] 담당없는 할 일에 담당 추가하기 & add django views.py 로직 수정

- static/css/login/mypage.css
- templates/login/mypage.html
> [FIX] mypage 수정

- apps/home/models.py
- apps/home/urls.py
- apps/home/views.py
- static/css/home/date_todo.css
- templates/home/date_todo/prev_date_todo.html
1) 오늘 이전 날짜 일은 오늘하기 누르면 오늘 날짜에 똑같은 Todo가 추가 되게 했습니당
: is_postpone만 true로 된 일
: date => 오늘 날짜
2) 오늘 이전 날짜에 있는 애는 오늘 하기를 눌렀고, 해당 일자에 미완료 된 일이라
: is_not_done_today가 true로 변경
=> css에서 border만 바뀌게 해놓음!
> [FIX] 오늘 이전 날짜 일 오늘하기 기능 구현

- apps/home/models.py
- apps/setting/urls.py
- apps/setting/views.py
- static/css/setting/myhome_detail.css
- static/css/setting/myhome_form.css
- static/js/setting/myhome_form.js
- templates/setting/myhome_detail.html
- templates/setting/myhome_form.html
1. 탭 디자인 통일
2. 집 검색할 때 초대 링크
3. 집 관리 - 프로필 사진 누르면 룸메이트 관리로 넘어가게
> [FEAT] QA 요청했던 거 수정

- apps/home/models.py
- apps/home/urls.py
- apps/home/views.py
- static/css/home/guideline.css
- static/css/home/living_rules.css
- static/js/home/living_rules.js
- templates/base.html
- templates/home/calendar.html
- templates/home/guideline.html
- templates/home/living_rules.html
- templates/home/living_rules_form.html
1. 가이드라인 -> 생활수칙 전달 view 수정
2. 가이드라인, 생활수칙 css 수정
3. 가이드라인 관련 url 모두 연결
> Feature guidelinepage check seyoun

- apps/home/models.py
- apps/login/urls.py
- apps/login/views.py
- config/settings.py
- static/js/login/sign_up.js
- templates/login/login.html
- templates/login/sign_up.html
- templates/login/user_update.html
이메일, 닉네임 중복확인 추가했습니다. 아직 많이 남아서 최대한 해보겠습니다...
> Feature signup check seungbin

- apps/login/views.py
- static/js/login/mypage.js
- templates/login/user_update.html
마이 페이지에서 닉네임 중복확인 체크 가능
남은 일 
1. templates에서 login쪽 html css 적용
2. 회원가입 중복체크 버그 수정 필요
3. 카카오 로그인 오류 수정
> [FIX] 중복확인 체크

- apps/home/models.py
- apps/home/views.py
- templates/home/date_todo/prev_date_todo.html
1) 아마도 todo 부분에서 profile_img_url을 주는 부분 로직이 이상했던 걸로 보입니다..
2) develop에 합쳐서 확인해주세요
> [FIX] 할 일 등록하기 & 수정하기&담당 추가하기 오류 해결

- apps/home/views.py
- static/js/home/date_todo.js
- templates/home/date_todo/date_todo.html
이거까지 체크하고 develop에서 받아서 다시 한번 체크해볼게욤
> [FIX]  할 일 등록 시 p tag 날라가는 거 수정 & 할 일 수정하기, 담당자 설정 프로필 사진 오류 수정 

- apps/home/models.py
- templates/setting/myhome_detail.html
- templates/setting/roommate_list.html
> [DESIGN] 설정 탭 서브네브바 밑줄

- apps/home/utils.py
- static/css/home/calendar.css
- static/css/style.css
- templates/home/calendar.html
- templates/home/home_base.html
캘린더 날짜별로 달성률 시각화 하는 부분 구현했습니다~
> [FEAT] 캘린더 날짜별 달성률 구현

- apps/home/models.py
- apps/home/views.py
- apps/login/forms.py
- apps/login/urls.py
- apps/login/views.py
- templates/login/mypage.html
- templates/login/profile_delete.html
> [FEAT] 회원탈퇴 기능 구현

- static/css/login/profile_delete.css
- templates/login/profile_delete.html
> [DESIGN] 회원탈퇴 CSS

- apps/home/models.py
- apps/home/views.py
- apps/login/views.py
- templates/login/mypage.html
> [FIX] navbar 알림 개수 최종 수정
